### ISSUE TITLE
Web App only Demo?

### ISSUE THREAD

**Issue by ATM-HSW** [WurthElektronik/Proteus-Connect#3]
The web app looks identical to the app on Android and iOs. However, after starting, it only shows a test device with testid123. Scanning is not successful. The dev kit with the firmware from FeatherWings/ProteusIIIFeatherWing is running. Under Android/iOS, the behaviour of the dev kit is as expected.
Should it also be possible to use the web app under Windows with a Chrome browser in the same way as under Android/iOS? Or is there only a demo built into the web app?

**Comment by wm-eisos** [comment]
Hey,

No the web app is not a demo, the test device shows up because you built it with the default configuration which is used for development if you run
`ionic serve --prod`
it will serve the web app in production mode which will cause the test device to be hidden. However even in the default development mode scanning should work fine.

P.S. only web browsers that support [web bluetooth api](https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API) will work otherwise you will get a message that the browser/device isn't supported.

regarding the scan can you explain more when you say that scanning is not successful?

Best Regards
Wajdi
